exports.render = function()
{
	return [
		"<!DOCTYPE html>",
		"<html>",
		"<head>",
		"<meta charset=\"utf-8\">",
		"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
		"<title>Q Dashboard</title>",
		"<style>",
		":root { --paper: #f6f1e8; --paper-2: #fbf7f0; --ink: #181512; --subtle: #6f665d; --line: rgba(24, 21, 18, 0.12); --line-strong: rgba(24, 21, 18, 0.24); --accent: #195c4f; --accent-soft: #dfece7; --warn: #8a302a; --warn-soft: #f6e3de; --shadow: 0 18px 45px rgba(34, 24, 12, 0.08); font-family: 'Avenir Next', 'Segoe UI', sans-serif; }",
		"* { box-sizing: border-box; }",
		"body { margin: 0; color: var(--ink); background: linear-gradient(180deg, #f4efe4 0%, #efe7da 42%, #e6ddcf 100%); }",
		"body::before { content: ''; position: fixed; inset: 0; background-image: linear-gradient(rgba(255,255,255,0.18) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.14) 1px, transparent 1px); background-size: 28px 28px; opacity: 0.25; pointer-events: none; }",
		".wrap { position: relative; max-width: 1220px; margin: 0 auto; padding: 28px 20px 72px; }",
		".hero { display: grid; grid-template-columns: minmax(0, 1.4fr) minmax(280px, 0.8fr); gap: 18px; align-items: stretch; margin-bottom: 18px; }",
		".heroCard, .railCard, .tableCard, .statCard { background: rgba(251, 247, 240, 0.78); backdrop-filter: blur(8px); border: 1px solid rgba(255,255,255,0.65); box-shadow: var(--shadow); }",
		".heroCard { border-radius: 28px; padding: 30px 30px 26px; background: linear-gradient(145deg, rgba(252,249,243,0.96), rgba(243,235,224,0.9)); }",
		".eyebrow { font-size: 12px; letter-spacing: 0.18em; text-transform: uppercase; color: var(--subtle); margin: 0 0 14px; }",
		"h1 { margin: 0; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(34px, 5vw, 58px); font-weight: 600; line-height: 0.96; letter-spacing: -0.03em; max-width: 8ch; }",
		".heroCard p { max-width: 56ch; color: var(--subtle); font-size: 15px; line-height: 1.6; margin: 14px 0 0; }",
		".railCard { border-radius: 24px; padding: 22px; display: flex; flex-direction: column; justify-content: space-between; background: linear-gradient(180deg, rgba(24,21,18,0.94), rgba(34,31,27,0.9)); color: #f4eee6; }",
		".railLabel { font-size: 11px; letter-spacing: 0.16em; text-transform: uppercase; opacity: 0.68; }",
		".railValue { font-family: Georgia, 'Times New Roman', serif; font-size: 54px; line-height: 1; margin: 18px 0 10px; }",
		".railMeta { font-size: 14px; color: rgba(244, 238, 230, 0.72); line-height: 1.5; }",
		".grid { display: grid; gap: 14px; grid-template-columns: repeat(4, minmax(0, 1fr)); margin-bottom: 18px; }",
		".statCard { border-radius: 20px; padding: 18px 18px 16px; }",
		".statLabel { font-size: 12px; text-transform: uppercase; letter-spacing: 0.14em; color: var(--subtle); margin-bottom: 12px; }",
		".metric { font-family: Georgia, 'Times New Roman', serif; font-size: 40px; line-height: 1; letter-spacing: -0.03em; }",
		".metricNote { margin-top: 8px; font-size: 13px; color: var(--subtle); }",
		".tableCard { border-radius: 24px; padding: 18px 18px 12px; margin-top: 18px; }",
		".sectionTop { display: flex; align-items: end; justify-content: space-between; gap: 18px; margin-bottom: 10px; padding-bottom: 10px; border-bottom: 1px solid var(--line); }",
		".sectionTop h2 { margin: 0; font-size: 24px; font-family: Georgia, 'Times New Roman', serif; font-weight: 600; letter-spacing: -0.02em; }",
		".sectionTop span { color: var(--subtle); font-size: 13px; }",
		".tableWrap { overflow-x: auto; }",
		"table { width: 100%; border-collapse: collapse; font-size: 14px; }",
		"th, td { text-align: left; padding: 12px 10px; border-bottom: 1px solid var(--line); vertical-align: top; }",
		"th { font-size: 11px; text-transform: uppercase; letter-spacing: 0.14em; color: var(--subtle); font-weight: 600; }",
		"tbody tr:hover { background: rgba(25, 92, 79, 0.045); }",
		".toolbar { display: flex; gap: 10px; flex-wrap: wrap; align-items: center; margin: 14px 0 14px; }",
		"input, select { border: 1px solid var(--line); border-radius: 14px; padding: 10px 12px; background: rgba(255,255,255,0.7); color: var(--ink); min-height: 42px; }",
		"input:focus, select:focus { outline: none; border-color: var(--line-strong); box-shadow: 0 0 0 4px rgba(25, 92, 79, 0.08); }",
		"button { border: 0; background: var(--accent); color: white; padding: 10px 14px; border-radius: 14px; cursor: pointer; font-weight: 600; letter-spacing: 0.01em; transition: transform 140ms ease, opacity 140ms ease, background 140ms ease; }",
		"button:hover { transform: translateY(-1px); opacity: 0.96; }",
		"button.warn { background: var(--warn); }",
		".chip { display: inline-flex; align-items: center; gap: 6px; padding: 6px 10px; border-radius: 999px; font-size: 12px; font-weight: 600; background: var(--accent-soft); color: var(--accent); }",
		".chip.fail { background: var(--warn-soft); color: var(--warn); }",
		".mono { font-family: 'SFMono-Regular', 'Menlo', monospace; font-size: 12px; }",
		".muted { color: var(--subtle); }",
		".actions { display: flex; gap: 8px; flex-wrap: wrap; }",
		".activityList { display: grid; gap: 10px; }",
		".activityRow { display: grid; grid-template-columns: 110px 170px 1fr; gap: 12px; align-items: start; padding: 10px 0; border-bottom: 1px solid var(--line); }",
		".activityRow:last-child { border-bottom: 0; }",
		"@media (max-width: 980px) { .hero { grid-template-columns: 1fr; } .grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }",
		"@media (max-width: 720px) { .wrap { padding: 18px 14px 56px; } .heroCard, .railCard, .tableCard, .statCard { border-radius: 18px; } .grid { grid-template-columns: 1fr; } .sectionTop { align-items: start; flex-direction: column; } th, td { padding: 10px 8px; } .activityRow { grid-template-columns: 1fr; gap: 4px; } }",
		"</style>",
		"</head>",
		"<body>",
		"<div class=\"wrap\">",
		"<div class=\"hero\">",
		"<section class=\"heroCard\">",
		"<div class=\"eyebrow\">Queue Operations</div>",
		"<h1>Operational view for live queue traffic.</h1>",
		"<p>Monitor queue pressure, inspect failed jobs and move dead-letter messages back into circulation without leaving the service.</p>",
		"</section>",
		"<aside class=\"railCard\">",
		"<div>",
		"<div class=\"railLabel\">Console</div>",
		"<div class=\"railValue\">Q</div>",
		"</div>",
		"<div class=\"railMeta\">Dashboard and admin API are served from the same process as the queue ingress. Refreshes every five seconds.</div>",
		"</aside>",
		"</div>",
		"<div class=\"grid\" id=\"stats\"></div>",
		"<section class=\"tableCard\">",
		"<div class=\"sectionTop\"><div><h2>Queues</h2><span>Current state across configured queue names.</span></div><div class=\"chip\">Live snapshot</div></div>",
		"<div class=\"tableWrap\"><table><thead><tr><th>Name</th><th>Total</th><th>New</th><th>Waiting</th><th>Error</th><th>Fail</th><th>Updated</th></tr></thead><tbody id=\"queues\"></tbody></table></div>",
		"</section>",
		"<section class=\"tableCard\">",
		"<div class=\"sectionTop\"><div><h2>Messages</h2><span>Filter by queue or status, then requeue or dead-letter directly.</span></div><div class=\"chip fail\">Mutable controls</div></div>",
		"<div class=\"toolbar\"><input id=\"queueFilter\" placeholder=\"Queue\"><select id=\"statusFilter\"><option value=\"\">All statuses</option><option value=\"new\">new</option><option value=\"waiting\">waiting</option><option value=\"error\">error</option><option value=\"fail\">fail</option><option value=\"success\">success</option></select><button id=\"reload\">Reload</button></div>",
		"<div class=\"tableWrap\"><table><thead><tr><th>ID</th><th>Queue</th><th>Status</th><th>Verb</th><th>URL</th><th>Updated</th><th>Actions</th></tr></thead><tbody id=\"messages\"></tbody></table></div>",
		"</section>",
		"<section class=\"tableCard\">",
		"<div class=\"sectionTop\"><div><h2>Activity</h2><span>Recent queue events including queued, success, retry, dead-letter and delete.</span></div><div class=\"chip\">Realtime</div></div>",
		"<div class=\"activityList\" id=\"activity\"></div>",
		"</section>",
		"</div>",
		"<script>",
		"async function getJson(url){ const response = await fetch(url); return response.json(); }",
		"async function post(url){ const response = await fetch(url, { method: 'POST' }); return response.json(); }",
		"function metricCard(label, value, note){ return `<div class=\"statCard\"><div class=\"statLabel\">${label}</div><div class=\"metric\">${value}</div><div class=\"metricNote\">${note}</div></div>`; }",
		"function statusChip(status){ const isFail = status === 'fail' || status === 'error'; return `<span class=\"chip ${isFail ? 'fail' : ''}\">${status}</span>`; }",
		"function formatDateTime(value){ if (value === undefined || value === null || value === '') { return ''; } let parsed = value; if (typeof parsed === 'string') { parsed = parsed.trim(); } const asNumber = Number(parsed); let date; if (!Number.isNaN(asNumber)) { const millis = asNumber < 1000000000000 ? asNumber * 1000 : asNumber; date = new Date(millis); } else { date = new Date(parsed); } if (Number.isNaN(date.getTime())) { return String(value); } return date.toLocaleString('sv-SE', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' }); }",
		"let stream = null;",
		"function renderQueues(data){ document.getElementById('stats').innerHTML = [metricCard('Queues', data.queues.length, 'Configured and auto-created lanes'), metricCard('Waiting', data.stats.TotalWaitingMessages || 0, 'Messages not yet completed'), metricCard('Errors', data.stats.MessagesWithError || 0, 'Currently in retry state'), metricCard('Active Dispatches', data.stats.ActiveDispatches || 0, 'In-flight worker load')].join(''); document.getElementById('queues').innerHTML = data.queues.map(queue => `<tr><td><strong>${queue.Name}</strong></td><td>${queue.TotalMessages || 0}</td><td>${queue.NewMessages || 0}</td><td>${queue.WaitingMessages || 0}</td><td>${queue.ErrorMessages || 0}</td><td>${queue.FailedMessages || 0}</td><td class=\"mono muted\">${formatDateTime(queue.Updated)}</td></tr>`).join(''); }",
		"function renderMessages(data){ document.getElementById('messages').innerHTML = data.messages.map(message => `<tr><td class=\"mono\">${message.id}</td><td><strong>${message.Queue}</strong></td><td>${statusChip(message.Status)}</td><td>${message.Verb}</td><td class=\"mono\">${message.Url}</td><td class=\"mono muted\">${formatDateTime(message.Updated)}</td><td><div class=\"actions\"><button onclick=\"requeue(${message.id})\">Requeue</button><button class=\"warn\" onclick=\"deadLetter(${message.id})\">Dead-letter</button></div></td></tr>`).join(''); }",
		"function renderActivity(data){ document.getElementById('activity').innerHTML = data.events.map(event => `<div class=\"activityRow\"><div class=\"mono muted\">${formatDateTime(event.Created)}</div><div>${statusChip(event.Status || event.EventType || 'event')} <span class=\"mono\">#${event.MessageId || '-'}</span></div><div><strong>${event.Queue || 'queue-less'}</strong><div class=\"muted\">${event.Detail || event.EventType || ''}</div></div></div>`).join(''); }",
		"function applySnapshot(data){ renderQueues(data); renderMessages(data); renderActivity(data); }",
		"async function loadSnapshot(){ const queue = encodeURIComponent(document.getElementById('queueFilter').value); const status = encodeURIComponent(document.getElementById('statusFilter').value); const data = await getJson(`/admin/api/stream-snapshot?queue=${queue}&status=${status}&limit=50`); applySnapshot(data); }",
		"function connectStream(){ const queue = encodeURIComponent(document.getElementById('queueFilter').value); const status = encodeURIComponent(document.getElementById('statusFilter').value); if (stream) { stream.close(); } stream = new EventSource(`/admin/api/stream?queue=${queue}&status=${status}&limit=50`); stream.addEventListener('snapshot', function(event){ applySnapshot(JSON.parse(event.data)); }); stream.onerror = function(){ if (stream) { stream.close(); } setTimeout(connectStream, 1000); }; }",
		"async function requeue(id){ await post(`/admin/api/messages/${id}/requeue`); }",
		"async function deadLetter(id){ await post(`/admin/api/messages/${id}/dead-letter`); }",
		"document.getElementById('reload').addEventListener('click', function(){ loadSnapshot(); connectStream(); });",
		"document.getElementById('queueFilter').addEventListener('change', function(){ loadSnapshot(); connectStream(); });",
		"document.getElementById('statusFilter').addEventListener('change', function(){ loadSnapshot(); connectStream(); });",
		"loadSnapshot(); connectStream();",
		"</script>",
		"</body>",
		"</html>"
	].join('');
}
